services:
  postgres:
    image: postgres:17-alpine
    container_name: lesto-postgres
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  identity-service:
    build:
      context: ../../src/IdentityService
      dockerfile: Dockerfile
    container_name: lesto-identity
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5001:8080"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  order-service:
    build:
      context: ../../src/OrderService
      dockerfile: Dockerfile
    container_name: lesto-order
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5002:8080"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  api-gateway:
    build:
      context: ../../src/ApiGateway
      dockerfile: Dockerfile
    container_name: lesto-gateway
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5000:8080"
    environment:
      - ReverseProxy__Clusters__identity-cluster__Destinations__destination1__Address=http://identity-service:8080
      # Adicionamos aqui a ligação do Gateway para o contentor do Order Service
      - ReverseProxy__Clusters__order-cluster__Destinations__destination1__Address=http://order-service:8080
    depends_on:
      - identity-service
      - order-service

volumes:
  postgres_data: