// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderService.Data;

#nullable disable

namespace OrderService.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260929104158_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderService.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourierId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationPointId")
                        .HasColumnType("uuid");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OriginPointId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RecipientData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DestinationPointId");

                    b.HasIndex("OriginPointId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderService.Models.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Points");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8b3c9a2-5f6e-4b1a-8c2d-9e7f3a1b4c6d"),
                            Latitude = 41.5503,
                            Longitude = -8.4199999999999999,
                            Name = "Ponto Braga Centro"
                        },
                        new
                        {
                            Id = new Guid("a1f4e7c2-9b8d-4a3f-6c5e-2b1d9a8c7e3f"),
                            Latitude = 41.561399999999999,
                            Longitude = -8.3972999999999995,
                            Name = "Ponto Universidade Minho"
                        },
                        new
                        {
                            Id = new Guid("c3e2d1f4-8a9b-4c7e-5d6f-3b2a1c9e8d7f"),
                            Latitude = 41.536000000000001,
                            Longitude = -8.6250999999999998,
                            Name = "Ponto Barcelos"
                        },
                        new
                        {
                            Id = new Guid("f9e8d7c6-b5a4-4f3e-2d1c-9b8a7c6e5d4f"),
                            Latitude = 41.536700000000003,
                            Longitude = -8.6277000000000008,
                            Name = "Ponto IPCA"
                        },
                        new
                        {
                            Id = new Guid("e5d4c3b2-a1f9-4e8d-7c6b-5a4f3e2d1c9b"),
                            Latitude = 41.407899999999998,
                            Longitude = -8.5192999999999994,
                            Name = "Ponto Famalicão"
                        },
                        new
                        {
                            Id = new Guid("b2a1c9e8-d7f6-4e5d-8c9b-0a1f2e3d4c5b"),
                            Latitude = 41.444400000000002,
                            Longitude = -8.2960999999999991,
                            Name = "Ponto Guimarães"
                        });
                });

            modelBuilder.Entity("OrderService.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Key = "PesoMaximoKg",
                            Value = "30"
                        });
                });

            modelBuilder.Entity("OrderService.Models.Order", b =>
                {
                    b.HasOne("OrderService.Models.Point", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderService.Models.Point", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });
#pragma warning restore 612, 618
        }
    }
}
